### ISSUE TITLE
Cannot download all 11 frames features

### ISSUE THREAD

**Issue by bearshr** [zeeshank95/GVSR#4]
I tried several times to download the features, but only a small part of the 50G features could be downloaded before aborting the download.
Could you please provide a zip file of all features instead of a folder?

**Comment by Darshansingh11** [comment]
Hi,

Please find the updated link of the [zip file](https://iiitaphyd-my.sharepoint.com/:u:/g/personal/lakshmipathi_balaji_research_iiit_ac_in/ETGCnb58rORJnZuyIJ-dLjYBIKx1PExkx5etvr2exBcHOA?e=YoELTZ&download=1).

**Comment by zeeshank95** [comment]
This is the updated [link](https://iiitaphyd-my.sharepoint.com/:u:/g/personal/lakshmipathi_balaji_research_iiit_ac_in/ETGCnb58rORJnZuyIJ-dLjYBIKx1PExkx5etvr2exBcHOA?e=YoELTZ&download=1)
